### ISSUE TITLE
Need help: Why my JS and CSS files are not loaded when deployed with teh same steps as you followed 

### ISSUE THREAD

**Issue by SandeepKumarYaramchitti** [mkrtchian/reading-notes#103]
Any help on this appreciated?

**Comment by mkrtchian** [comment]
Hello,

Can you give the link of your repo?

**Comment by SandeepKumarYaramchitti** [comment]
I am all set with this and the issue was related to a wrong path defined.

Your project is really good for reference and I am sure many would benefit from here
